### ISSUE TITLE
Plugin doesn't create webp version for intermediate image sizes

### ISSUE THREAD

**Issue by jaapmarcus** [vontainment/v-wordpress-image-optimize#2]
When uploading a new image  the main image is correctly converted how ever any image created for the them set via: https://developer.wordpress.org/reference/functions/add_image_size/

Are not generated...

Is there a way to solve this issue?

Did try to look for it how ever wasn't able to find it

**Comment by vontainment** [comment]
I've been distracted by the projects but I'll get back to this one real quick. I have to do it too chat and find the right hook but I should be able to tie into the process that creates the thumbnails. Also I might be if I create a WP cron job That check service often that there's a webp version for each image and thumbnail and also deletes any orphaned webps. That way activation would be careful as well. And if there's any server side issue then stopped something from getting converted. The server was restarted and the background were running that they are taken care of.

**Comment by jaapmarcus** [comment]
PR https://github.com/vontainment/v-wordpress-image-optimize/pull/3

Should fix the issue :)

**Comment by vontainment** [comment]
Yes, thank you.
I just did a few update  of my own and added an optional wp cron job that makes sure there are not orphaned or unoptimized images only if 'VWPIMGOP' defined as 'true'. basically a quick way to turn on a nd off a way to fix any previously created images.

and set it so it will log errors though wordpresses default debug log if it is turned on

**Comment by vontainment** [comment]
I wounder if its worth adding AVIF as an option that can be enabled?

**Comment by jaapmarcus** [comment]
It would require 8.1 https://www.php.net/manual/en/function.imageavif.php

It might be worth imo

**Comment by vontainment** [comment]
Using Linux server side "go-avif" would be the better way to go. Just like the other conversations id use serverside software not wp or PHP to do the conversion and using the avif just like webp would be left to being handled in webserver config. So it wouldn't require any particular version of PHP this way. The original point was plug-in was to handle image optimization through server side software to avoid using PHP to do it because in the end it's more efficient with resources.
